name: FarmingUpgrade
author: Torm
description: Upgraded farming mechanics.
version: 1.6.0
main: no.hyp.farmingupgrade.FarmingUpgradePlugin
api-version: 1.16
permissions:
  farmingupgrade:
    description: Every FarmingUpgrade permission.
    default: op
    children: [farmingupgrade.administrator]
  farmingupgrade.administrator:
    description: Ability to reload the configuration and use the farmingupgrade command.
    default: op
commands:
  farmingupgrade:
    description: FarmingUpgrade help and configuration reload.
    permission: farmingupgrade.administrator
